name: "POSSE links to Mastodon"
on:
  schedule:
    # https://crontab.guru/#1/37_*_*_*_*
    - cron: "1/37 * * * *"
  workflow_dispatch:

env:
  TYPE: "links"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Mastodon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 📥
        uses: actions/checkout@v3

      - name: POSSE ${{ env.TYPE }} to Mastodon 🦣
        uses: nhoizey/github-action-jsonfeed-to-mastodon@v1
        with:
          feedUrl: "https://nicolas-hoizey.com/feeds/mastodon/${{ env.TYPE }}.json"
          mastodonInstance: ${{ secrets.MASTODON_INSTANCE }}
          mastodonToken: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          cacheFile: "posse-mastodon-${{ env.TYPE }}.json"
          cacheTimestampFile: "posse-mastodon-${{ env.TYPE }}-timestamp.json"
          # 23 hours between links
          globalDelayToots: 1380
          nbTootsPerItem: 2
          # 8.5 days between same links
          delayTootsSameItem: 12240

      - name: Pull any changes from Git 📥
        run: git pull

      - name: Commit and push 📤
        uses: stefanzweifel/git-auto-commit-action@v4
