name: "POSSE links to Mastodon"
on:
  schedule:
    # At every 16th minute from 1 through 59 past every hour
    # https://crontab.guru/#1/16_*_*_*_*
    - cron: "1/16 * * * *"
  workflow_dispatch:

env:
  TYPE: "links"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Mastodon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 📥
        uses: actions/checkout@v3

      - name: POSSE ${{ env.TYPE }} to Mastodon 🦣
        uses: nhoizey/github-action-jsonfeed-to-mastodon@v1
        with:
          feedUrl: "https://nicolas-hoizey.com/feeds/mastodon/${{ env.TYPE }}.json"
          mastodonInstance: ${{ secrets.TEST_MASTODON_INSTANCE }}
          mastodonToken: ${{ secrets.TEST_MASTODON_ACCESS_TOKEN }}
          cacheFile: "posse-mastodon-${{ env.TYPE }}.json"
          cacheTimestampFile: "posse-mastodon-${{ env.TYPE }}-timestamp.json"
          globalDelayToots: 15

      - name: Pull any changes from Git 📥
        run: git pull

      - name: Commit and push 📤
        uses: stefanzweifel/git-auto-commit-action@v4
